### ISSUE TITLE
Error while create UAP-AppStore-Package (Windows 10)

### ISSUE THREAD

**Issue by MysticEmpires** [autofac/Autofac#673]
I got this Error while try to create an AppStore-Package from an Windows 10 UAP-App:

1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(1408,5): warning : Assembly 'Autofac' requests the address of the virtual method 'Type.IsAssignableFrom(Type)' which is not available in the targeted .NET platform. Please ask the author of 'Autofac' to provide an implementation that can be used in the currently targeted .NET platform.

**Comment by MysticEmpires** [comment]
Ok fixed in the Beta, My Fail

**Comment by mayerc-MSFT** [comment]
what Beta?  Can you please clarify?

I'm seeing the same warning in my project's build.

**Comment by Viper2k4** [comment]
https://www.nuget.org/packages/Autofac/

look there a Betas as well

**Comment by MMalikKhan** [comment]
I am still seeing the above issue even in the RC2, any updates if this works with the latest UWP toolset 1.3.2 and 10568?
"ILTransform_0017: Assembly 'Autofac' requests the address of the virtual method 'Type.IsAssignableFrom(Type)' which is not available in the targeted .NET platform. Please ask the author of 'Autofac' to provide an implementation that can be used in the currently targeted .NET platform."

**Comment by tillig** [comment]
Can you post a repro or tell us how to reproduce it? File - New Project, or more than that?

**Comment by alexmg** [comment]
We previously had a specific target for UWP but replaced that with netstandard1.1 in our RC2 release.

It's supposed to support UWP according to the table below:

https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

However, this [comment](https://github.com/dotnet/cli/issues/2549#issuecomment-221028555 ) suggests it isn't actually supported in RC2 though.

> RC2 should not be used for targeting UWP. There was a long list of bugs that didn't meet the bar for fixing in RC2 so we fixed them in RC3.

> To use the RC3 packages make sure you pull them from the https://dotnet.myget.org/F/dotnet-core/api/v3/index.json feed.

We'll probably upgrade to RC3 on the develop branch soon so you could start testing this from our MyGet feed.
